=== kotucz/kotucz-playground/kotuc3d/kotuc/kotuc3d.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--
    DTD for kotuc 3d system.
-->

<!ELEMENT unitlist (unit+)>
<!ATTLIST unitlist 
            name    CDATA    #IMPLIED
            parts   CDATA    #REQUIRED
>
<!ELEMENT unit (v*, p*)>
<!ATTLIST unit 
            name	CDATA	#IMPLIED
            verts	CDATA	#REQUIRED
            pols	CDATA	#REQUIRED
>

<!ELEMENT v EMPTY>
<!ATTLIST v 
            id	CDATA	#IMPLIED	
            x	CDATA	#REQUIRED
            y	CDATA	#REQUIRED
            z	CDATA	#REQUIRED
>

<!ELEMENT p EMPTY>
<!ATTLIST p 
            color	CDATA	#IMPLIED
            v1		CDATA	#REQUIRED
            v2		CDATA	#REQUIRED
            v3		CDATA	#REQUIRED
>

=== kotucz/kotucz-playground/kotuc3d/kotuc/unitList01.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE unitlist SYSTEM "kotuc3d.dtd" [
  <!ENTITY faceColor "0xFF8800">
  <!ENTITY bodyColor "0xAAFF88">
  <!ENTITY armorColor "0x333355">
  <!ENTITY knifeColor "0x777799">    
]>
<unitlist name="hero" parts="3">
	<unit name="head" verts="6" pols="8">
		<v id="0"	x="0"	y="0"	z="0"/>
		<v id="1"	x="10"	y="10"	z="10"/>
		<v id="2"	x="-10"	y="10"	z="10"/>
		<v id="3"	x="-10"	y="-10"	z="10"/>
		<v id="4"	x="10"	y="-10"	z="10"/>
		<v id="5"	x="0"	y="0"	z="20"/>
		
		<!-- down4 -->
		<p color="&faceColor;" v1="0" v2="1" v3="2"/>
		<p color="&faceColor;" v1="0" v2="3" v3="2"/>
		<p color="&faceColor;" v1="0" v2="3" v3="4"/>
		<p color="&faceColor;" v1="0" v2="1" v3="4"/>
		
		<!-- up4 -->
		<p color="&armorColor;" v1="5" v2="1" v3="2"/>
		<p color="&armorColor;" v1="5" v2="3" v3="2"/>
		<p color="&armorColor;" v1="5" v2="3" v3="4"/>
		<p color="&armorColor;" v1="5" v2="1" v3="4"/>
	</unit>
	<unit name="body" verts="6" pols="8">
		<v id="0" x="0" y="0" z="0"/>
		<v id="1" x="20" y="20" z="20"/>
		<v id="2" x="-20" y="20" z="20"/>
		<v id="3" x="-20" y="-20" z="20"/>
		<v id="4" x="20" y="-20" z="20"/>
		<v id="5" x="0" y="0" z="40"/>
		
		<!-- down4 -->
		<p color="0xFF0000" v1="0" v2="1" v3="2"/>
		<p color="0xFFFF00" v1="0" v2="3" v3="2"/>
		<p color="0x0000FF" v1="0" v2="3" v3="4"/>
		<p color="&armorColor;" v1="0" v2="1" v3="4"/>
		
		<!-- up4 -->
		<p color="0xFF0000" v1="5" v2="1" v3="2"/>
		<p color="0xFFFF00" v1="5" v2="3" v3="2"/>
		<p color="0x0000FF" v1="5" v2="3" v3="4"/>
		<p color="&armorColor;" v1="5" v2="1" v3="4"/>
	</unit>
	<unit name="knife" verts="6" pols="8">
		<v id="0" x="0" y="0" z="0"/>
		<v id="1" x="-5" y="-10" z="15"/>
		<v id="2" x="5" y="-10" z="15"/>
		<v id="3" x="5" y="10" z="15"/>
		<v id="4" x="-5" y="10" z="15"/>
		<v id="5" x="0" y="0" z="80"/>
		
		<!-- down4 -->
		<p color="&knifeColor;" v1="0" v2="1" v3="2"/>
		<p color="&knifeColor;" v1="0" v2="3" v3="2"/>
		<p color="&knifeColor;" v1="0" v2="3" v3="4"/>
		<p color="&knifeColor;" v1="0" v2="1" v3="4"/>
		
		<!-- up4 -->
		<p color="&knifeColor;" v1="5" v2="1" v3="2"/>
		<p color="&knifeColor;" v1="5" v2="3" v3="2"/>
		<p color="&knifeColor;" v1="5" v2="3" v3="4"/>
		<p color="&knifeColor;" v1="5" v2="1" v3="4"/>
	</unit>
</unitlist>
