=== kotucz/kotucz-playground/trunk/Chaos/classes/data/location.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--
    DTD for kotuc 3d system.
-->

<!ELEMENT location ((player, phasemap?),(tree|house|darkball)*)>
<!ATTLIST location 
			width CDATA #IMPLIED
			height CDATA #IMPLIED
			random CDATA #IMPLIED			
>

<!ELEMENT tree EMPTY>
<!ATTLIST tree 
            x	CDATA	#REQUIRED
            y	CDATA	#REQUIRED
>

<!ELEMENT house EMPTY>
<!ATTLIST house 
            x	CDATA	#REQUIRED	
            y	CDATA	#REQUIRED
            rotz	CDATA	#REQUIRED
>

<!ELEMENT player (item*)>
<!ATTLIST player 
            x	CDATA	#REQUIRED
            y	CDATA	#REQUIRED
            z	CDATA	#REQUIRED
            rotz CDATA	#REQUIRED
>

<!ELEMENT darkball (item*)>
<!ATTLIST darkball 
            x	CDATA	#REQUIRED
            y	CDATA	#REQUIRED
            z	CDATA	#REQUIRED
            rotz CDATA	#REQUIRED
>


<!ELEMENT item EMPTY>
<!ATTLIST item
            x	CDATA	#IMPLIED
            y	CDATA	#IMPLIED
            z	CDATA	#IMPLIED
            equiped CDATA	#IMPLIED
            type CDATA	#IMPLIED
            name CDATA	#IMPLIED
>

<!ELEMENT phasemap (phasex*)>
<!ATTLIST phasemap
            widthx	CDATA	#IMPLIED
>

<!ELEMENT phasex (phasey*)>
<!ATTLIST phasex
            widthy	CDATA	#IMPLIED
>

<!ELEMENT phasey (phase*)>
<!ATTLIST phasey
            height	CDATA	#IMPLIED
>

<!ELEMENT phase EMPTY>
<!ATTLIST phase
            type	(air|water|solid) #IMPLIED
>

=== kotucz/kotucz-playground/trunk/Chaos/chaos3d-old/location1.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE location SYSTEM "location.dtd" [
    
]>
<location width="20" height="20" random="0.3">
		
	<player x="4.5" y="3.5" z="2" rotz="1.3">
		<item type="weapon" name="knife" equiped="yes"/>
	</player>

<!--	
	<phasemap widthx="3">
		<phasex widthy="5">
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
		</phasex>
		<phasex widthy="5">
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
		</phasex>
		<phasex widthy="5">
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
			<phasey>
				<phase type="solid"/>
			</phasey>
			<phasey height="2">
				<phase type="water"/>
				<phase type="water"/>
			</phasey>
		</phasex>
	</phasemap>
	-->
	<tree x="11.0" y="6.0"/>
	<tree x="6.3" y="8.0"/>
	<tree x="9.0" y="8.5"/>
	<tree x="7.0" y="10.0"/>
	<tree x="10.0" y="7.0"/>
	<tree x="9.0" y="7.0"/>
	
	<house x="7" y="7.2" rotz="1.3"/>
	
	<house x="12" y="7.2" rotz="2.3"/>
	
	<house x="7" y="13.2" rotz="3.3"/>
	
		
	<darkball x="9.0" y="8.2" z="2" rotz="1.3">
		<item type="weapon" name="oldknife" equiped="no"/>
	</darkball>
		
	<darkball x="7" y="7.2" z="2" rotz="1.3"/>
		
	<darkball x="9.0" y="8.2" z="2" rotz="1.3">
		<item type="weapon" name="oldknife" equiped="no"/>
	</darkball>
		
	<darkball x="7" y="7.2" z="2" rotz="1.3"/>
	
	<darkball x="9.0" y="8.2" z="2" rotz="1.3">
		<item type="weapon" name="oldknife" equiped="no"/>
	</darkball>
		
	<darkball x="7" y="7.2" z="2" rotz="1.3"/>
	
</location>
